name: uas_pemmob
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  get_it: ^7.7.0
  retrofit: ^4.1.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  file_picker: ^8.0.5
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/women.png
    - assets/men.png
    - assets/kids.png
    - assets/logo_olg.jpg

